version: '3'

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${PACT_BROKER_YAML_USERNAME}
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker
    links:
      - postgres
    ports:
      - '80:80'
    environment:
      PACT_BROKER_DATABASE_USERNAME: ${PACT_BROKER_YAML_USERNAME}
      PACT_BROKER_DATABASE_PASSWORD: ''
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http
