module.exports = {
    applicantDetailsPageTitle: 'Enter your name',
    firstName: 'Bob',
    lastName: 'Ice',
    confidentialityPageTitle: 'Keeping your contact details private for',
    confidentialitySubHeading: 'Do the other people named in this application (the respondents) know any of your contact details?',
    keepingConfidentialContactPageTitle: 'Keeping your contact details private for',
    keepingConfidentialContactSubHeading: 'Do you want to keep your contact details private from the other people named in the application (the respondents)?',
    confidentialitySummarySubHeading: 'The court will keep your contact details private',
    confidentialitySummarySubHeading2: 'What the court will do',
    provideDetailsPageTitle: 'Provide details for',
    provideDetailsPageTitleSubHeading: 'Have you changed your name?',
    previousName: 'Zack Leo',
    placeOfBirthSubHeading: 'Your place of birth',
    placeOfBirth: 'London',
    relationshipToChildPageTitle: 'relationship to',
    addressDetailsOfApplicantPageTitle: 'Address of',
    addressHintText: 'Current postcode',
    postcode: 'B11LS',  
    day: '21',
    month: '07',
    year: '2001',
    addressLookUpPageTitle: 'Select Address of',
    lookUpOption: 'APARTMENT 1, WESTSIDE ONE, 22, SUFFOLK STREET QUEENSWAY, BIRMINGHAM, B1 1LS', 
    confirmAddressPageTitle: 'Address of',
    confirmAddressSubHeading: 'Have you lived at this address for more than 5 years?',
    contactDetailsPageTitle: 'Contact details of',
    contactDetailsSubHeading: 'Can the court leave you a voicemail?',
    email: 'testc100@test.com',
    phoneNumber: '07123456789',
    contactPreferencesPageTitle: 'Contact Preferences for',
};