module.exports = {
    cyaTitle: 'Check your Answers',
    caseName: 'Case name',
    locationDetails: 'Location details',
    typeOfApplication: 'Type of application',
    legalRepDetails: 'Legal representative details',
    permissionApplication: 'Permission to make the application',
    miam: 'MIAM: Mediation Information and Assessment Meeting',
    miamAttendance: 'MIAM attendance',
    miamExemption: 'MIAM exemption',
    askingCourtDecide: "What you're asking the court to decide",
    hearingDetails: 'Hearing details',
    detailsOfPeopleApp: 'Details of the people in the application',
    childDetails: "Children's details",
    additionalChildDetails: 'Additional details about the children',
    otherChildDetails: 'Other Children details',
    otherChild: 'Child 1',
    applicantDetails: 'Details of the applicants',
    applicantOneDetails: 'Applicant 1 - Your details',
    respondentDetails: 'Details of the respondents',
    respondentOneDetails: 'Respondent 1',
    otherPeopleDetails: 'Details of the other people in the application',
    otherPersonOneDetails: 'Other person 1',
    whereChildLive: 'Where the children live',
    pastAndCurrentProceedings: 'Past and current proceeding',
    safetyConcerns: 'Safety concerns',
    childSafetyConcerns: 'Safety concerns: the children in the application',
    applicantSafetyConcerns: 'Safety concern: your safety',
    otherSafetyConcerns: 'Safety concern: other concerns that you have',
    internationalElements: 'International elements',
    reasonableAdjustments: 'Support you need during your case',
    helpWithFees: 'Help with Fees',
    statementOfTruth: 'Statement of Truth',
    confirmStatementTruth: 'Confirm before you submit the application',
    applicationSubmittedSuccess: 'Your application has been submitted',
    applicationCaseNo: 'Case number',
}