module.exports = {
    childDetailsNamePageTitle: 'Enter the names of the children',
    childFirstName: 'Jon',
    childLastName: 'Snow',
    childDetailsDOBPageTitle: 'Provide details for',
    childDetailsDOBSubHeading: 'Gender',
    decisionsCourtToResolvePageTitle: 'Which of the decisions you’re asking the court to resolve relate to',
    parentalResponsibilityPageTitle: 'Parental responsibility for',
    furtherInformationPageTitle: 'Further Information',
    furtherInformationSubHeading: 'Are any of the children the subject of a child protection plan?',
    otherChildrenPageTitle: 'Do you or any respondents have other children who are not part of this application?',  
    otherChildrenNamePageTitle: 'Enter the other child’s name', 
    testingText: 'Testing text area',
    day: '20',
    month: '08',
    year: '2006',
    firstName: 'Alice',
    surname: 'Web',
};