module.exports = {
    otherProceedingsPageTitle: 'Are the children involved in any emergency protection, care or supervision proceedings (or have they been)?',
    attendingMiamPageTitle: 'Attending a Mediation Information and Assessment Meeting MIAM',
    attendingMiamSubHeading: 'When you don’t have to attend a MIAM',
    attendedMiamPageTitle: 'Have you attended a Mediation Information and Assessment Meeting (MIAM)?',
    medidatorConfirmedPageTitle: 'Has a mediator confirmed that you do not need to attend a MIAM?',
    validReasonsMiamPageTitle: 'Do you have a valid reason for not attending a MIAM?',
    validReasonWhatPageTitle: 'MIAM exemptions',
    evidenceDomesticAbusePageTitle: 'Evidence of domestic abuse',
    providingEvidenceDomestic: 'Providing evidence of domestic abuse',
    canYouProvideEvidence: 'Can you provide evidence?',
    uploadDomesticEvidence: 'Upload evidence of domestic abuse',
    evidenceChildProtectionPageTitle: 'Child protection concerns',
    urgentHearingTitle: 'Urgency',
    previousAttendMiamPageTitle: 'Previous MIAM attendance or non-court dispute resolution (NCDR)',
    confirmValidReasonPageTitle: 'Other reason for not attending a MIAM',
    evidenceAttendMIAMUpload: 'Upload evidence of attending a MIAM or NCDR',
    dontHaveToAttendMiamPageTitle: 'You’ve told us you have a valid reason for not attending a MIAM',
    altDontHaveToAttendMiamPageTitle: 'You’ve told us you have a valid reason for not attending a MIAM',
    reasonForNotAttendingMIAM: 'Reasons given for not attending a MIAM:',
    reasonDomesticAbuse: 'Domestic abuse',
    reasonChildProtection: 'Child protection concerns',
    reasonNCDR: 'Previous attendance of a MIAM, or non-court dispute resolution (NCDR)',
    reasonOther: 'Other reason',
    miamDocumentSignedPageTitle: 'Do you have a document signed by the mediator?',
    uploadMiamCertificatePageTitle: 'Upload your MIAM certificate',
    miamCertificateSummaryPageTitle: 'Your MIAM certificate has been uploaded',
    buttonContinue: 'Continue',
};