module.exports = {
    otherProceedingsPageTitle: 'Are the children involved in any emergency protection, care or supervision proceedings (or have they been)?',
    attendingMiamPageTitle: 'Attending a Mediation Information and Assessment Meeting MIAM',
    attendingMiamSubHeading: 'When you don’t have to attend a MIAM',
    attendedMiamPageTitle: 'Have you attended a Mediation Information and Assessment Meeting (MIAM)?',
    medidatorConfirmedPageTitle: 'Has a mediator confirmed that you do not need to attend a MIAM?',
    validReasonsMiamPageTitle: 'Do you have valid reasons for not attending a MIAM?',
    validReasonWhatPageTitle: 'What are your valid reasons for not attending a MIAM?',
    evidenceDomesticAbusePageTitle: 'Do you have any of the following evidence of domestic violence or abuse?',
    evidenceChildProtectionPageTitle: 'What evidence of child protection concerns do you have?',
    urgentHearingTitle: 'Do you require an urgent hearing because you or the children are at risk for any of the following reasons?',
    previousAttendMiamPageTitle: 'Can you confirm that you previously attended a MIAM, or had a valid reason not to attend?',
    confirmValidReasonPageTitle: 'Can you confirm that any of the other valid reasons for not attending a MIAM apply in your case?',
    dontHaveToAttendMiamPageTitle: 'You don’t have to attend a MIAM',
    altDontHaveToAttendMiamPageTitle: 'You do not have to attend a MIAM',
    buttonContinue: 'Continue',
};