module.exports = {
    otherPersonPageTitle: 'Is there anyone else who should know about your application?',
    otherPersonNamePageTitle: "Enter the other person's name",
    firstName: 'Taylor',
    lastName: 'Snow',
    otherPersonDetailsPageTitle: 'Provide details for',
    haveTheyChangedTheirNameText: 'Have they changed their name?',
    genderText: 'Gender',
    otherPersonDetailsDOBText: 'Date of birth',
    day: '25',
    month: '07',
    year: '1963',
    otherPersonRelationshipPageTitle: 'relationship to',
    addressOfOtherPersonPageTitle: 'Address of',
    addressOfOtherPersonSubHeading: 'Current postcode',
    postcode: 'MK9 3DX',
    addressLookUpPageTitle: 'Select Address of',
    addressLookUpSubHeading: 'Select an address',
    lookUpOption: '417, SAXON GATE EAST, MILTON KEYNES, MK9 3DX', 
    confirmAddressPageTitle: 'Address details of',
    childMainlyLiveWith: 'Select the person that the child lives with most of the time.',
    childLivingArrangements: "We need this information so that the court has a complete understanding of the child’s living arrang"
};
