module.exports = {
    enterRespondentDetailsPageTitle: "Enter the respondent's name",
    firstName: 'Ben',
    lastName: 'Coal',
    provideDetailsForRespondentPageTitle: 'Provide details for',
    provideDetailsForRespondentSubHeading: 'Have they changed their name?',
    provideDetailsForRespondentGender: 'Gender',
    provideDetailsForRespondentDOB: 'Date of birth',
    placeOfBirthText: 'Place of birth',
    day: '13',
    month: '07',
    year: '1988',
    placeOfBirth: 'Kent',
    respondentRelationshipPageTitle: 'relationship to',
    addressOfRespondentPageTitle: 'Address of',
    addressOfRespondentSubHeading: 'Current postcode',
    postcode: 'CV32 4DG',
    addressLookUpPageTitle: 'Select Address of',
    addressLookUpSubHeading: 'Select an address',
    lookUpOption: 'APARTMENT 1, GEORGE HOUSE, 1, PARADE, LEAMINGTON SPA, CV32 4DG', 
    addressDetailsPageTitle: 'Address details of',
    addressDetailsTextBoxText: 'I dont know where they currently live',
    addressDetailsSubHeading: 'Have they lived at this address for more than 5 years?',
    addressDetailsNoHintText: 'Please provide details of all previous addresses for the last 5 years below, including the dates and starting with the most recent',
    previousAddressPostCode: 'T3 5ST',
    contactDetailsOfRespPageTitle: 'Contact details of ',
};