module.exports = {
    testingText: 'Testing Text',
    safetyConcernsPageTitle: 'Safety concerns',
    concernsSafety: 'Do you have any concerns for your safety or the safety of the children?',
    concernsSafetyYesInfo: 'The information you give will be considered as part of your application. If you need to make an application for a domestic abuse injunction. you can do this separately.',
    concernAboutWho: 'Who are you concerned about?',
    whatBehaviourChildren: 'What type of behaviour have the children experienced or are at risk of experiencing?',
    describePhysicalAbuseTitle: 'Briefly describe the physical abuse against the children if you feel able to',
    whichChildren: 'Which children are you concerned about? (optional)',
    seekHelpYesText: 'Contact 999 if there is an emergency.',
    whyChildAbduction: 'Why do you think the children may be abducted or kept outside the UK without your consent?',
    doChildrenHavePassport: 'Do any of the children have a passport?',
    childrenPassportDetails: 'Provide details of the children’s passports',
    passportOfficeNotified: 'Has the passport office been notified?',
    childAbductedBefore: 'Have the children been abducted or kept outside the UK without your consent before?',
    previousAbductionDetailsTitle: 'Provide details of the previous abductions',
    whatBehaviourApplicantTitle: 'What type of behaviour have you experienced or are at risk of experiencing?',
    describePhysicalAbuseApplicantTitle: 'Briefly describe the physical abuse if you feel able to',
    describeEmotionalAbuseApplicantTitle: 'Briefly describe the emotional abuse if you feel able to',
    childImpactedDrugAlcohol: 'Have the children been impacted by drug, alcohol or substance abuse?',
    otherConcernsSafetyTitle: 'Do you have any other concerns about the children’s safety and wellbeing?',
    courtToDoTitle: 'What do you want the court to do to keep you and the children safe?',
    contactWithChildTitle: 'Contact between the children and the other people in this application',
    childSpendingTimeSubtitle: 'Do you agree to the children spending time with the other people in this application?',
    contactOtherWaysSubtitle: 'Do you agree to the other people in this application being in touch with the children in other ways?',
    buttonContinue: 'Continue',
};