/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
/* eslint-disable @typescript-eslint/no-unused-vars */
import { ReasonableAdjustmentElement } from './reasonableAdjustmentContent.util';

/**
 * It returns an object containing the contents of the English and Welsh versions of the page,
 * depending on the language selected
 * @returns A function that returns an object.
 */
const TestReasonableAdjustmentElement = language => {
  const opContents = {
    en: () => {
      return {
        accessToilet: 'Accessible toilet',
        appropriateLighting: 'Appropriate lighting',
        appropriateLighting_subfield: 'Describe what you need',
        assistanceGuideDog: 'Assistance / guide dog',
        attendingCourtHeading: 'Would you be able to take part in hearings by video and phone?',
        audioTranslationDocuments: 'Audio translation of documents',
        brailleDocuments: 'Braille documents',
        caption: 'Reasonable adjustments',
        communicationHelp: 'I need help communicating and understanding',
        communicationHelpHeading: 'I need help communicating and understanding',
        communicationHelpHint: 'for example, hearing, speaking or interpretation',
        communicationHelpOther: 'Other',
        describeWhatNeeded: 'Describe what you need',
        differentTypeChair: 'A different type of chair',
        differentTypeChairSubFieldHint: 'For example, a chair with back support',
        differentTypeChair_subfield: 'Describe why you need',
        disabilityRequirementHeading:
          'Do you have a physical, mental or learning disability or health condition that means you need support during your case?',
        documentHelpOther: 'Other',
        documentInformationHeading: 'I need documents in an alternative format',
        documentsHelp: 'I need documents in an alternative format',
        documentsHelpHint: 'for example, braille or different colours and text sizes',
        easyReadFormatDocuments: 'Documents in Easy Read format',
        easyReadFormatDocumentsHint: 'information written in simple language with pictures',
        emailInformation: 'Information emailed to me',
        errors: '',
        explanationOfCourt: "Explanation of the court and who's in the room at the hearing",
        extraSupport: 'I need to bring support with me to a hearing',
        extraSupportHint: 'for example, someone you know or an assistance dog',
        feelComfortableHeading: 'I need something to feel comfortable during a court hearing',
        feelComfortableSupport: 'I need something to feel comfortable during a hearing',
        feelComfortableSupportHint: 'for example, extra breaks or extra space',
        feelComportableNoOption: 'No, I do not need any support at this time',
        feelComportableOther: 'Other',
        feelComportableOther_subfield: 'Describe what you need',
        friendFamilyMember: 'A friend or family member',
        friendFamilyMember_subfield: 'Tell us who you will bring',
        guideBuilding: 'Guiding in the building',
        headingTitle: 'I need help travelling to, or moving around court buildings',
        hearingLoop: 'Hearing loop (hearing enhancement system)',
        helpTravellingMovingBuildingSupport: 'I need help travelling to, or moving around court buildings',
        helpTravellingMovingBuildingSupportHint:
          'for example, access and mobility support if a hearing takes place in person',
        helpUsingLift: 'Help using a lift',
        infraredReceiver: 'Infrared receiver (hearing enhancement system)',
        intermediary: 'Intermediary',
        intermediaryHint:
          'a person to help you if you have communication needs by providing professional support to participate in a hearing',
        langaugeRequirementHeading: 'Do you have any language requirements?',
        largePrintDocuments: 'Documents in large print',
        line1: 'Consider in-person, phone or video, in case your preferred hearing type is not possible',
        line2: 'by video (where you can join from a place suitable to you)',
        line3: 'by phone',
        lipSpeaker: 'Lip speaker',
        lipSpeakerHint: 'hearing person who has been trained to be easily lip read',
        needExtraTime: 'Extra time to think and explain myself',
        needInterpreterInCertainLanguage: 'I need an interpreter in a certain language',
        needInterpreterInCertainLanguage_subfield:
          'Give details of the language you require (including dialect, if applicable)',
        needToBeClosedWithSpeaker: 'Need to be close to who is speaking',
        noLanguageRequirements: 'No, I do not have any language requirements at this time',
        noSafetyRequirements: 'No, I do not have any safety requirements at this time',
        noSupportRequired: 'No, I do not need any support at this time',
        noVideoAndPhoneHearing: 'No, I cannot take part in either video or phone hearings',
        noVideoAndPhoneHearingReason: 'If you choose this option please tell us why in case we can assist you',
        noVideoAndPhoneHearing_subfield: 'Explain why you are unable to take part in video or phone hearings',
        paragraph1: 'If your case goes to a hearing, it can take place either:',
        paragraph2: 'Some hearings use a combination of these methods. The approach taken will be decided by a judge.',
        parkingSpace: 'Parking space close to the venue',
        parkingSpace_subfield: 'Describe why you need this',
        phoneHearing: 'Yes, I can take part in phone hearings',
        readAndWriteInWelsh: 'I need to read and write in Welsh',
        readOutDocuments: 'Documents read out to me',
        regularBreaks: 'Regular breaks',
        screenWithOtherPeople: 'Screens so you and the other people in the case cannot see each other',
        screenWithOtherPeopleHint: 'This needs to be approved by a judge',
        select_all_apply: 'Select all that apply to you',
        separateExitEntrance: 'Separate exits and entrances',
        separateToilets: 'Separate toilets',
        separateWaitingRoom: 'Separate waiting room',
        signLanguageInterpreter: 'Sign Language interpreter',
        spaceUpAndMoveAround: 'Space to be able to get up and move around',
        speakInWelsh: 'I need to speak in Welsh',
        specialArrangementsHeading: 'Do you or the children need special arrangements at court?',
        specialArrangementsOther: 'Other',
        specialArrangementsOther_subfield: 'Provide details of what you or the children need',
        specifiedColorDocuments: 'Documents in a specified colour',
        speechToTextReporter: 'Speech to text reporter (palantypist)',
        supportCourtHeading: 'I need to bring support with me to a court hearing',
        supportCourtNoOption: 'No, I do not need any support at this time',
        supportCourtOther: 'Other',
        supportCourtOther_subfield: 'Describe what you need',
        supportWorkerCarer: 'A support worker or carer',
        supportWorkerCarer_subfield: 'Tell us who you will bring',
        therapyAnimal: 'Therapy animal',
        therapyAnimal_subfield: 'Describe what you need',
        travellingCourtHeading: 'I need help travelling to, or moving around court buildings',
        travellingCourtNoOption: 'No, I do not need any support at this time',
        travellingCourtOther: 'Other',
        travellingCourtOther_subfield: 'Describe what you need',
        venueWheelchair: 'Use of venue wheelchair',
        videoHearing: 'Yes, I can take part in video hearings',
        videoLinks: 'Video links',
        videoLinksHint: 'This needs to be approved by a judge',
        visitCourtBeforeHearing: 'Visit to court before the hearing',
        wheelchairAccess: 'Step free / wheelchair access',
      };
    },
    cy: () => {
      return {
        accessToilet: 'Toiledau hygyrch',
        appropriateLighting: 'Golau priodol',
        appropriateLighting_subfield: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        assistanceGuideDog: 'Ci cymorth / ci tywys',
        attendingCourtHeading: 'A fyddech chi’n gallu cymryd rhan mewn gwrandawiadau drwy fideo a dros y ffôn?',
        audioTranslationDocuments: 'Cyfieithiad sain o ddogfennau',
        brailleDocuments: 'Dogfennau Braille',
        caption: 'Addasiadau rhesymol',
        communicationHelp: 'Rwyf angen cymorth gyda chyfathrebu a deall pethau',
        communicationHelpHeading: 'Rwyf angen cymorth gyda chyfathrebu a deall pethau',
        communicationHelpHint: 'er enghraifft, gwrando, siarad neu gymorth gan gyfieithydd/dehonglydd',
        communicationHelpOther: 'Arall',
        describeWhatNeeded: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        differentTypeChair: 'Math gwahanol o gadair',
        differentTypeChairSubFieldHint: 'Er enghraifft, cadair â chymorth cefn',
        differentTypeChair_subfield: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        disabilityRequirementHeading:
          'A oes gennych anabledd corfforol, meddyliol neu addysgol neu gyflwr iechyd sy’n golygu bod angen cymorth arnoch yn ystod eich achos?',
        documentHelpOther: 'Arall',
        documentInformationHeading: 'Rwyf angen dogfennau mewn fformat arall',
        documentsHelp: 'Rwyf angen dogfennau mewn fformat arall',
        documentsHelpHint: 'er enghraifft, Braille neu wahanol liwiau a maint testun ',
        easyReadFormatDocuments: 'Dogfennau mewn fformat hawdd i’w darllen',
        easyReadFormatDocumentsHint: "Gwybodaeth wedi'i hysgrifennu mewn iaith syml gyda lluniau",
        emailInformation: 'Gwybodaeth yn cael ei hanfon ataf drwy e-bost',
        errors: '',
        explanationOfCourt: 'Esboniad o osodiad y llys a phwy fydd yn yr ystafell wrandawiadau',
        extraSupport: 'Rwyf angen dod â rhywun efo fi i fy nghefnogi mewn gwrandawiad',
        extraSupportHint: "er enghraifft, rhywun rydych chi'n ei adnabod neu gi cymorth",
        feelComfortableHeading: 'Rwyf angen rhywbeth i wneud i mi deimlo’n gyfforddus yn ystod gwrandawiad llys',
        feelComfortableSupport: 'Rwyf angen rhywbeth i wneud i mi deimlo’n gyfforddus yn ystod gwrandawiad',
        feelComfortableSupportHint: 'er enghraifft, seibiannau ychwanegol neu mwy o le',
        feelComportableNoOption: 'Nac oes, nid oes arnaf angen unrhyw gymorth ar hyn o bryd',
        feelComportableOther: 'Arall',
        feelComportableOther_subfield: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        friendFamilyMember: "ffrind neu aelod o'r teulu",
        friendFamilyMember_subfield: 'Dywedwch wrthym pwy fyddwch yn dod efo chi',
        guideBuilding: 'Cymorth i fynd o amgylch yr adeilad',
        headingTitle: 'Rwyf angen cymorth i deithio i, neu symud o gwmpas adeiladau’r llys',
        hearingLoop: 'Dolen sain (system gwella clyw)',
        helpTravellingMovingBuildingSupport: 'Rwyf angen cymorth i deithio i, neu symud o gwmpas adeiladau’r llys',
        helpTravellingMovingBuildingSupportHint:
          'er enghraifft, cymorth gyda mynediad a symudedd os bydd gwrandawiad yn cael ei gynnal wyneb yn wyneb',
        helpUsingLift: 'Help i ddefnyddio lifft',
        infraredReceiver: 'Derbynnydd isgoch (system gwella clyw)',
        intermediary: 'Cyfryngwr',
        intermediaryHint:
          'Rhywun i’ch helpu os oes gennych anghenion cyfathrebu drwy ddarparu cymorth proffesiynol i gymryd rhan mewn gwrandawiad',
        langaugeRequirementHeading: 'A oes gennych chi unrhyw ofynion ieithyddol?',
        largePrintDocuments: 'Dogfennau mewn print bras',
        line1:
          'Ystyriwch wrandawiad wyneb yn wyneb, dros y ffôn neu drwy fideo, rhag ofn nad yw’r math o wrandawiad a ffefrir gennych yn bosibl',
        line2: "trwy fideo (lle gallwch chi ymuno o leoliad sy'n addas i chi)",
        line3: 'dros y ffôn',
        lipSpeaker: 'Darllen gwefusau',
        lipSpeakerHint: 'Clywed rhywun sydd wedi cael ei hyfforddi i allu darllen gwefusau yn rhwydd',
        needExtraTime: 'Amser ychwanegol i feddwl ac egluro fy hun',
        needInterpreterInCertainLanguage: "Rwy'n dymuno cael cyfieithydd mewn iaith benodol",
        needInterpreterInCertainLanguage_subfield:
          'Rhowch fanylion yr iaith sydd ei hangen arnoch (gan gynnwys tafodiaith, os yn berthnasol)',
        needToBeClosedWithSpeaker: "Angen bod yn agos at bwy bynnag sy'n siarad",
        noLanguageRequirements: 'Nac oes, nid oes gennyf unrhyw ofynion ieithyddol ar hyn o bryd',
        noSafetyRequirements: 'Nac oes, nid oes arnaf angen unrhyw ofynion o ran diogelwch ar hyn o bryd',
        noSupportRequired: 'Nac oes, nid oes arnaf angen unrhyw gymorth ar hyn o bryd',
        noVideoAndPhoneHearing: 'Ni allaf gymryd rhan mewn gwrandawiad fideo na gwrandawiad dros y ffôn',
        noVideoAndPhoneHearingReason:
          'Os dewiswch yr opsiwn hwn, dywedwch wrthym pam rhag ofn y gallwn eich cynorthwyo',
        noVideoAndPhoneHearing_subfield:
          'Esboniwch pam nad ydych yn gallu cymryd rhan mewn gwrandawiad drwy fideo na gwrandawiad dros y ffôn',
        paragraph1: 'Os bydd eich achos yn mynd i wrandawiad, gellir ei gynnal naill ai:',
        paragraph2:
          "Mae rhai gwrandawiadau yn defnyddio cyfuniad o'r dulliau hyn. Y Barnwr fydd yn penderfynu pa ddull fydd yn cael ei ddefnyddio.",
        parkingSpace: "Lle parcio yn agos i'r lleoliad",
        parkingSpace_subfield: 'Disgrifiwch pam fod arnoch angen hyn',
        phoneHearing: 'Gallaf gymryd rhan mewn gwrandawiad dros y ffôn',
        readAndWriteInWelsh: "Rwy'n dymuno darllen ac ysgrifennu yn Gymraeg",
        readOutDocuments: 'Dogfennau yn cael eu darllen yn uchel i mi',
        regularBreaks: 'Seibiannau rheolaidd',
        screenWithOtherPeople: 'Sgriniau i atal chi a’r bobl eraill yn yr achos rhag gweld eich gilydd',
        screenWithOtherPeopleHint: 'Mae angen i farnwr gymeradwyo hyn',
        select_all_apply: "Dewiswch bob un sy'n berthnasol i chi",
        separateExitEntrance: "Drysau ar wahân i fynd i mewn ac allan o'r llys",
        separateToilets: 'Toiledau ar wahân',
        separateWaitingRoom: 'Ystafell aros ar wahân',
        serviceName: 'Trefniadau plant',
        signLanguageInterpreter: 'Dehonglydd iaith arwyddion',
        spaceUpAndMoveAround: 'Lle i allu codi a symud o gwmpas',
        speakInWelsh: "Rwy'n dymuno siarad Cymraeg",
        specialArrangementsHeading: "Ydych chi neu'r plant angen trefniadau arbennig yn y llys?",
        specialArrangementsOther: 'Arall',
        specialArrangementsOther_subfield: 'Darparwch fanylion am yr hyn rydych chi neu’r plant ei angen',
        specifiedColorDocuments: 'Dogfennau mewn lliw penodol',
        speechToTextReporter: 'Cofnodwr iaith lafar i destun (palanteipydd)',
        supportCourtHeading: 'Rwyf eisiau dod â rhywun efo fi i fy nghefnogi mewn gwrandawiad llys',
        supportCourtNoOption: 'Nac oes, nid oes arnaf angen unrhyw gymorth ar hyn o bryd',
        supportCourtOther: 'Arall',
        supportCourtOther_subfield: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        supportWorkerCarer: 'Gweithiwr cymorth neu ofalwr',
        supportWorkerCarer_subfield: 'Dywedwch wrthym pwy fyddwch yn dod efo chi',
        therapyAnimal: 'Anifail therapi',
        therapyAnimal_subfield: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        travellingCourtHeading: 'Rwyf angen cymorth i deithio i, neu symud o gwmpas adeiladau’r llys',
        travellingCourtNoOption: 'Nac oes, nid oes arnaf angen unrhyw gymorth ar hyn o bryd',
        travellingCourtOther: 'Arall',
        travellingCourtOther_subfield: 'Disgrifiwch yr hyn sydd ei angen arnoch',
        venueWheelchair: 'Y gallu i ddefnyddio cadair olwyn a geir yn y lleoliad',
        videoHearing: 'Gallaf gymryd rhan mewn gwrandawiad fideo',
        videoLinks: 'Cyswllt fideo',
        videoLinksHint: 'Mae angen i farnwr gymeradwyo hyn',
        visitCourtBeforeHearing: "Ymweld â'r llys cyn y gwrandawiad",
        wheelchairAccess: 'Dim gris / mynediad ar gyfer cadair olwyn',
      };
    },
  };
  return language === 'en' ? opContents.en() : opContents.cy();
};

describe('test cases for otherProceedingsContents', () => {
  test('english contents', () => {
    expect(ReasonableAdjustmentElement('en')).toStrictEqual(TestReasonableAdjustmentElement('en'));
  });
  test('Welsh contents', () => {
    expect(ReasonableAdjustmentElement('cy')).toStrictEqual(TestReasonableAdjustmentElement('cy'));
  });
});
