export const applicationDetailsfieldType = {
    proceedingsStart: 'String',
    proceedingsStartOrder: 'String',
    courtProceedingsOrders: 'String',
    emergencyOrderOptions: 'YesOrNo',
    'emergencyOrder.caseNoDetails': 'String',
    'emergencyOrder.orderDateDetails': 'Date',
    'emergencyOrder.orderTimeDetails': 'String',
    'emergencyOrder.currentOrderDetails': 'YesOrNo',
    'emergencyOrder.issueOrderDetails': 'String',
    supervisionOrderOption: 'YesOrNo',
    'supervisionOrder.caseNoDetails': 'String',
    'supervisionOrder.orderDateDetails': 'Date',
    'supervisionOrder.orderTimeDetails': 'String',
    'supervisionOrder.currentOrderDetails': 'YesOrNo',
    'supervisionOrder.issueOrderDetails': 'String',
    careOrderOptions: 'YesOrNo',
    'careOrder.caseNoDetails': 'String',
    'careOrder.orderDateDetails': 'Date',
    'careOrder.orderTimeDetails': 'String',
    'careOrder.currentOrderDetails': 'YesOrNo',
    'careOrder.issueOrderDetails': 'String',
    childAbductionOrderOption: 'YesOrNo',
    'childAbductionOrder.caseNoDetails': 'String',
    'childAbductionOrder.orderDateDetails': 'Date',
    'childAbductionOrder.orderTimeDetails': 'String',
    'childAbductionOrder.currentOrderDetails': 'YesOrNo',
    'childAbductionOrder.issueOrderDetails': 'String',
    caOrderOption: 'YesOrNo',
    'caOrder.caseNoDetails': 'String',
    'caOrder.orderDateDetails': 'Date',
    'caOrder.orderTimeDetails': 'String',
    'caOrder.currentOrderDetails': 'YesOrNo',
    'caOrder.issueOrderDetails': 'String',
    financialOrderOption: 'YesOrNo',
    'financialOrder.caseNoDetails': 'String',
    'financialOrder.orderDateDetails': 'Date',
    'financialOrder.orderTimeDetails': 'String',
    'financialOrder.currentOrderDetails': 'YesOrNo',
    'financialOrder.issueOrderDetails': 'String',
    nonmolestationOrderOption: 'YesOrNo',
    'nonmolestationOrder.caseNoDetails': 'String',
    'nonmolestationOrder.orderDateDetails': 'Date',
    'nonmolestationOrder.orderTimeDetails': 'String',
    'nonmolestationOrder.currentOrderDetails': 'YesOrNo',
    'nonmolestationOrder.issueOrderDetails': 'String',
    occupationalOrderOptions: 'YesOrNo',
    'occupationOrder.caseNoDetails': 'String',
    'occupationOrder.orderDateDetails': 'Date',
    'occupationOrder.orderTimeDetails': 'String',
    'occupationOrder.currentOrderDetails': 'YesOrNo',
    'occupationOrder.issueOrderDetails': 'String',
    marraigeOrderOptions: 'YesOrNo',
    'marraigeOrder.caseNoDetails': 'String',
    'marraigeOrder.orderDateDetails': 'Date',
    'marraigeOrder.orderTimeDetails': 'String',
    'marraigeOrder.currentOrderDetails': 'YesOrNo',
    'marraigeOrder.issueOrderDetails': 'String',
    restrainingOrderOptions: 'YesOrNo',
    'restrainingOrder.caseNoDetails': 'String',
    'restrainingOrder.orderDateDetails': 'Date',
    'restrainingOrder.orderTimeDetails': 'String',
    'restrainingOrder.currentOrderDetails': 'YesOrNo',
    'restrainingOrder.issueOrderDetails': 'String',
    injuctiveOrderOptions: 'YesOrNo',
    'injuctiveOrder.caseNoDetails': 'String',
    'injuctiveOrder.orderDateDetails': 'Date',
    'injuctiveOrder.orderTimeDetails': 'String',
    'injuctiveOrder.currentOrderDetails': 'YesOrNo',
    'injuctiveOrder.issueOrderDetails': 'String',
    underTakingOrderOptions: 'YesOrNo',
    'underTakingOrder.caseNoDetails': 'String',
    'underTakingOrder.orderDateDetails': 'Date',
    'underTakingOrder.orderTimeDetails': 'String',
    'underTakingOrder.currentOrderDetails': 'YesOrNo',
    'underTakingOrder.issueOrderDetails': 'String',
  };
  
export const consentFieldType = {
    doYouConsent: 'String',
    applicationReceivedDate: 'Date',
    courtPermission: 'String',
    courtOrderDetails: 'String',
  };
  
export const applicationDetailsfieldTypeMiam = {
    miamStart: 'String',
    miamWillingness: 'String',
    miamNotWillingExplnation: 'String',
  };
  
export const keepYourDetailsfieldType = {
    detailsKnown: 'String',
    startAlternative: 'String',
  };
  
export const confirmYourDetailsfieldType = {
    citizenUserFullName: 'String',
    citizenUserDateOfBirthText: 'String',
    citizenUserPlaceOfBirthText: 'String',
    citizenUserAddressText: 'String',
    citizenUserAddressHistory: 'String',
    citizenUserPhoneNumberText: 'String',
    citizenUserEmailAddressText: 'String',
    citizenUserSafeToCall: 'String',
  };
  
export const legalRepresantationFieldType = {
    legalRepresentation: 'String',
  };
  
export const inetnationlFactorFieldType = {
    start: 'String',
    iFactorsStartProvideDetails: 'String',
    parents: 'String',
    iFactorsParentsProvideDetails: 'String',
    jurisdiction: 'String',
    iFactorsJurisdictionProvideDetails: 'String',
    request: 'String',
    iFactorsRequestProvideDetails: 'String',
  };
  
export const safetyConcernsfieldType = {
    proceedingsStart: 'String',
  };
  
export const additionalInformationfieldType = {
    proceedingsStart: 'String',
  };
export const supportYouNeedFieldType={
    attendingToCourt: 'String',
    hearingDetails: 'String',
    languageRequirements: 'String',
    languageDetails: 'String',
    safetyArrangements: 'String',
    safetyArrangementsDetails: 'String',
    reasonableAdjustments:'String',
    docsSupport:'String',
    docsDetails: 'String',
    largePrintDetails: 'String',
    otherDetails: 'String',
    helpCommunication: 'String',
    describeSignLanguageDetails: 'String',
    describeOtherNeed: 'String',
    courtHearing: 'String',
    supportWorkerDetails: 'String',
    familyProviderDetails: 'String',
    therapyDetails: 'String',
    communicationSupportOther: 'String',
    courtComfort: 'String',
    lightingProvideDetails: 'String',
    otherProvideDetails: 'String',
    travellingToCourt: 'String',
    parkingDetails: 'String',
    differentChairDetails: 'String',
    travellingOtherDetails: 'String',
}