export const respondent_tasklist_items_en = {
  do_you_have_legal_representation: 'Do you have a legal representative?',
  do_you_consent_to_the_application: 'Do you consent to the application?',
  keep_your_details_private: 'Keep your details private',
  confirm_or_edit_your_contact_details: 'Confirm or edit your contact details',
  support_you_need_during_your_case: 'Support you need during your case',
  mediation_miam: 'Mediation(MIAM)',
  current_or_previous_proceedings: 'Current or previous proceedings',
  your_safety: 'Your safety',
  childrens_safety: "The children's safety",
  abduction_concerns: 'Abduction concerns',
  other_concerns: 'Other concerns',
  what_do_you_want_the_court_to_do: 'What do you want the court to do?',
  international_factors: 'International element',
};

export const respondent_tasklist_items_cy = {
  do_you_have_legal_representation: 'Oes gennych chi gynrychiolydd cyfreithiol?',
  do_you_consent_to_the_application: "Ydych chi'n cydsynio i'r cais?",
  keep_your_details_private: 'Cadw eich manylion yn breifat',
  confirm_or_edit_your_contact_details: 'Cadarnhau neu olygu eich manylion cyswllt',
  support_you_need_during_your_case: 'Cymorth sydd ei angen arnoch yn ystod eich achos chi',
  mediation_miam: 'Cyfryngu (MIAM)',
  current_or_previous_proceedings: 'Achos cyfredol neu flaenorol',
  your_safety: 'Your safety',
  childrens_safety: "The children's safety",
  abduction_concerns: 'Abduction concerns',
  other_concerns: 'Other concerns',
  what_do_you_want_the_court_to_do: 'What do you want the court to do?',
  international_factors: 'Elfennau rhyngwladol',
};
