services:
  authProvider:
    url: SERVICE_AUTH_PROVIDER_URL
    secret: SERVICE_AUTH_SECRET
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
port: PORT
session:
  redis:
    host: REDIS_HOST
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
