services:
  postcodeLookup:
    url: 'https://api.os.uk/search/places/v1'
    token: POSTCODE_TOKEN
  authProvider:
    url: SERVICE_AUTH_PROVIDER_URL
    secret: SERVICE_AUTH_SECRET
    microservice: 'prl_citizen_frontend'
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    citizenClientSecret: CITIZEN_IDAM_SECRET
    cosApiClientSecret: COS_API_IDAM_SECRET
    systemUsername: SYSTEM_UPDATE_USER_USERNAME
    systemPassword: SYSTEM_UPDATE_USER_PW
  citizen:
    uploadDocsEmail: UPLOAD_DOCUMENTS_EMAIL
  case:
    url: CCD_URL
  cos:
    url: COS_URL
  documentManagement:
    url: DOCUMENT_MANAGEMENT_URL
  equalityAndDiversity:
    name: 'Equality and Diversity Service'
    url: EQUALITY_URL
    tokenKey: PCQ_TOKEN
    pcqEnabled: PCQ_ENABLED
    path: '/service-endpoint'
    port: 4000
  reasonableAdjustments:
    url: REASONABLE_ADJUSTMENTS
  dgs:
    url: DGS_URL
port: PORT
session:
  redis:
    host: REDIS_HOST
  secureCookie: SECURE_COOKIE
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY

featureToggles:
  launchDarklyKey: LAUNCH_DARKLY_SDK_KEY
  c100Rebuild: C100_REBUILD_FLAG
  testingSupport: TESTING_SUPPORT_FLAG
  enableRAComponent: ENABLE_RA_COMPONENT

launchDarkly:
  offline: LAUNCH_DARKLY_OFFLINE_MODE
