services:
  authProvider:
    url: SERVICE_AUTH_PROVIDER_URL
    secret: SERVICE_AUTH_SECRET
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
  case:
    url: CCD_URL
  payments:
    url: PAYMENTS_API_URL
  feeLookup:
    url: FEE_LOOKUP_URL
  documentManagement:
    url: DOCUMENT_MANAGEMENT_URL
  equalityAndDiversity:
    url: EQUALITY_URL
    tokenKey: PCQ_TOKEN
    pcqEnabled: PCQ_ENABLED
port: PORT
session:
  redis:
    host: REDIS_HOST
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
localCourt:
  emailId:
    CHELMSFORD_FAMILY_COURT: CHELMSFORD_FAMILY_COURT_EMAIL
    OXFORD_FAMILY_COURT: OXFORD_FAMILY_COURT_EMAIL
    MEDWAY_FAMILY_COURT: MEDWAY_FAMILY_COURT_EMAIL
    PORTSMOUTH_FAMILY_COURT: PORTSMOUTH_FAMILY_COURT_EMAIL
    LEEDS_FAMILY_COURT: LEEDS_FAMILY_COURT_EMAIL
    NORTHAMPTON_FAMILY_COURT: NORTHAMPTON_FAMILY_COURT_EMAIL
    WORCESTER_FAMILY_COURT: WORCESTER_FAMILY_COURT_EMAIL
    NEWPORT_GWENT_FAMILY_COURT: NEWPORT_GWENT_FAMILY_COURT_EMAIL
    FALLBACK_EMAIL_ID: FALLBACK_EMAIL_ID_VALUE
