services:
  postcodeLookup:
    url: 'https://api.os.uk/search/places/v1'
    token: POSTCODE_TOKEN
  idam:
    authorizationURL: 'http://localhost:9002/login'
    tokenURL: 'http://localhost:5000/o/token'
  case:
    url: 'http://localhost:4452'
  payments:
    url: 'http://localhost:4401'
  equalityAndDiversity:
    url: 'http://localhost:4000'
