services:
  idam:
    authorizationURL: 'http://localhost:3501/login'
    tokenURL: 'http://localhost:5000/o/token'
  case:
    url: 'http://localhost:4452'
  payments:
    url: 'http://localhost:4401'
  equalityAndDiversity:
    url: 'http://localhost:4000'
