export const applicant_tasklist_items_all_docs_en = {
  view_all_orders_from_the_court_all_docs: 'View all orders from the court',
  applicant_request_for_child_arrangements: "<nameapplicantxxxxx>'s request for child arrangements",
  applicant_request_for_domestic_abuse: "<nameapplicantxxxxx>'s request for domestic abuse",
  applicant_allegations_of_harm_and_violence: "<nameapplicantxxxxx>'s allegations of harm and violence",
  applicant_response_to_other_side_allegation_of_harm:
    "<nameapplicantxxxxx>'s response to the other side's allegations of harm or violence",
  applicant_position_statements: "<nameapplicantxxxxx>'s position statements",
  applicant_witness_statements: "<nameapplicantxxxxx>'s witness statements",
  other_people_witness_statements: "Other people's witness statements",
  medical_reports: 'Medical reports',
  miam_certificate: 'MIAM certificate',
  applications_made_in_these_proceedings: 'Applications made in these proceedings',
  previous_orders_submitted: 'Previous orders submitted with application',
  letters_from_school: 'Letters from school',
  digital_downloads: 'Emails, screenshots, images and other media files',
  medical_records: 'Medical records',
  paternity_test_reports: 'Paternity test reports',
  drug_alcohol_tests: 'Drug and alcohol tests (toxicology)',
  police_disclosures: 'Police reports',
  witness_availability: 'Witness availability',
  tenancy_and_mortgage_availability: 'Tenancy and mortgage agreements',
  respondent_response_to_request_for_child_arrangements:
    "<namerespondentxxxxx>'s response to the request for child arrangements",
  respondent_response_for_domestic_abuse: "<namerespondentxxxxx>'s response to the request for domestic abuse",
  respondent_response_to_allegations_of_harm_and_violence:
    "<namerespondentxxxxx>'s response to the allegations of harm and violence",
  respondent_allegation_of_harm_and_violence: "<namerespondentxxxxx>'s allegations of harm and violence",
  applications_made_in_these_proceedings_respondent: 'Applications made in these proceedings',
  previous_orders_submitted_respondent: 'Previous orders submitted with application',
  letters_from_school_respondent: 'Letters from school',
  respondent_position_statements: "<namerespondentxxxxx>'s position statements",
  respondent_witness_statements: "<namerespondentxxxxx>'s witness statements",
  other_people_witness_statements_respondent: "Other people's witness statements",
  digital_downloads_respondent: 'Emails, screenshots, images and other media files',
  medical_records_respondent: 'Medical records',
  medical_reports_respondent: 'Medical reports',
  paternity_test_reports_respondent: 'Paternity test reports',
  drug_alcohol_tests_respondent: 'Drug and alcohol tests (toxicology)',
  police_disclosures_respondent: 'Police reports',
  witness_availability_respondent: 'Witness availability',
  safeguarding_letter: 'Safeguarding letter',
  section7_report: 'Section 7 report',
  section37_report: 'Section 37 report',
  risk_assessment_16a: '16a risk assessment',
  important_address_and_contact_details: 'Important information about your address and contact details',
  dna_reports: 'DNA reports',
  privacy_notice: 'Privacy notice',
  special_measures: 'Special measures',
  notice_of_hearing: 'Notice of hearing',
  support_you_need_during_your_case: 'Support you need during your case',
  other_documents: 'Other documents',
};

export const applicant_tasklist_items_all_docs_cy = {
  view_all_orders_from_the_court_all_docs: 'Gweld yr holl orchmynion gan y llys',
  applicant_request_for_child_arrangements: 'Cais <nameapplicantxxxxx> am drefniadau plant',
  applicant_request_for_domestic_abuse: "<nameapplicantxxxxx>'s request for domestic abuse",
  applicant_allegations_of_harm_and_violence: 'Honiadau <nameapplicantxxxxx> o niwed a thrais',
  applicant_response_to_other_side_allegation_of_harm:
    'Ymateb <nameapplicantxxxxx> i honiadau’r ochr arall o niwed a thrais',
  applicant_position_statements: 'Datganiadau safbwynt <nameapplicantxxxxx>',
  applicant_witness_statements: 'Datganiadau tyst <nameapplicantxxxxx>',
  other_people_witness_statements: 'Datganiadau tyst pobl eraill',
  medical_reports: 'Adroddiadau meddygol',
  miam_certificate: 'Tystysgrif MIAM',
  applications_made_in_these_proceedings: 'Ceisiadau a wnaed yn yr achos hwn',
  previous_orders_submitted: 'Gorchmynion blaenorol a gyflwynwyd gyda’r cais',
  letters_from_school: 'Llythyrau gan yr ysgol',
  digital_downloads: 'Negeseuon e-bost, cipluniau, delweddau a ffeiliau cyfryngau eraill',
  medical_records: 'Cofnodion meddygol',
  paternity_test_reports: 'Adroddiadau prawf tadogaeth',
  drug_alcohol_tests: 'Profion cyffuriau ag alcohol (tocsicoleg)',
  police_disclosures: 'Adroddiadau gan yr heddlu',
  witness_availability: 'Pryd fydd tystion ar gael',
  tenancy_and_mortgage_availability: 'Tenantiaeth a morgais',
  respondent_response_to_request_for_child_arrangements: 'Ymateb  <namerespondentxxxxx> i’r cais am drefniadau plant',
  respondent_response_for_domestic_abuse: "<namerespondentxxxxx>'s response to the request for domestic abuse -welsh",
  respondent_response_to_allegations_of_harm_and_violence:
    "<namerespondentxxxxx>'s response to the allegations of harm and violence -welsh",
  respondent_allegation_of_harm_and_violence: 'Honiadau <namerespondentxxxxx> o niwed a thrais',
  applications_made_in_these_proceedings_respondent: 'Ceisiadau a wnaed yn yr achos hwn',
  previous_orders_submitted_respondent: 'Gorchmynion blaenorol a gyflwynwyd gyda’r cais',
  letters_from_school_respondent: 'Llythyrau gan yr ysgol',
  respondent_position_statements: 'Datganiadau safbwynt <namerespondentxxxxx>',
  respondent_witness_statements: 'Datganiadau tyst <namerespondentxxxxx>',
  other_people_witness_statements_respondent: 'Datganiadau tyst pobl eraill',
  digital_downloads_respondent: 'Negeseuon e-bost, cipluniau, delweddau a ffeiliau cyfryngau eraill',
  medical_records_respondent: 'Cofnodion meddygol',
  medical_reports_respondent: 'Adroddiadau meddygol',
  paternity_test_reports_respondent: 'Adroddiadau prawf tadogaeth',
  drug_alcohol_tests_respondent: 'Profion cyffuriau ag alcohol (tocsicoleg)',
  police_disclosures_respondent: 'Adroddiadau gan yr heddlu',
  witness_availability_respondent: 'Pryd fydd tystion ar gael',
  safeguarding_letter: 'Llythyr diogelu',
  section7_report: 'Adroddiad Adran 7',
  section37_report: 'Adroddiad Adran 37',
  risk_assessment_16a: 'Asesiad risg 16a',
  important_address_and_contact_details: 'Gwybodaeth bwysig am eich cyfeiriad a’ch manylion cyswllt',
  dna_reports: 'Adroddiadau DNA',
  privacy_notice: 'Hysbysiad Preifatrwydd',
  special_measures: 'Mesurau arbennig',
  notice_of_hearing: 'Hysbysiad o Wrandawiad',
  support_you_need_during_your_case: 'Cefnogaeth sydd ei hangen arnoch yn ystod eich achos',
  other_documents: 'Dogfennau eraill',
};
