export const applicant_tasklist_items_all_docs_en = {
  view_all_orders_from_the_court_all_docs: 'View all orders from the court',
  applicant_request_for_child_arrangements: "<nameapplicantxxxxx>'s request for child arrangements",
  applicant_allegations_of_harm_and_violence: "<nameapplicantxxxxx>'s allegations of harm and violence",
  applicant_response_to_other_side_allegation_of_harm:
    "<nameapplicantxxxxx>'s response to the other side's allegations of harm or violence",
  applicant_position_statements: "<nameapplicantxxxxx>'s position statements",
  applicant_witness_statements: "<nameapplicantxxxxx>'s witness statements",
  other_people_witness_statements: "Other people's witness statements",
  medical_reports: 'Medical reports',
  miam_certificate: 'MIAM certificate',
  applications_made_in_these_proceedings: 'Applications made in these proceedings',
  previous_orders_submitted: 'Previous orders submitted with application',
  letters_from_school: 'Letters from school',
  digital_downloads: 'Emails, screenshots, images and other media files',
  photographic_evidence: 'Photographic evidence',
  mobile_phone_screenshots: 'Mobile phone screenshots',
  medical_records: 'Medical records',
  paternity_test_reports: 'Paternity test reports',
  drug_alcohol_tests: 'Drug and alcohol tests (toxicology)',
  police_disclosures: 'Police disclosures',
  witness_availability: 'Witness availability',
  respondent_response_to_request_for_child_arrangements:
    "<namerespondentxxxxx>'s response to the request for child arrangements",
  respondent_response_to_allegations_of_harm_and_violence:
    "<namerespondentxxxxx>'s response to the allegations of harm and violence",
  respondent_allegation_of_harm_and_violence: "<namerespondentxxxxx>'s allegations of harm and violence",
  applications_made_in_these_proceedings_respondent: 'Applications made in these proceedings',
  previous_orders_submitted_respondent: 'Previous orders submitted with application',
  letters_from_school_respondent: 'Letters from school',
  respondent_position_statements: "<namerespondentxxxxx>'s position statements",
  respondent_witness_statements: "<namerespondentxxxxx>'s witness statements",
  other_people_witness_statements_respondent: "Other people's witness statements",
  digital_downloads_respondent: 'Emails, screenshots, images and other media files',
  photographic_evidence_respondent: 'Photographic evidence',
  mobile_phone_screenshots_respondent: 'Mobile phone screenshots',
  medical_records_respondent: 'Medical records',
  medical_reports_respondent: 'Medical reports',
  paternity_test_reports_respondent: 'Paternity test reports',
  drug_alcohol_tests_respondent: 'Drug and alcohol tests (toxicology)',
  police_disclosures_respondent: 'Police disclosures',
  witness_availability_respondent: 'Witness availability',
  safeguarding_letter: 'Safeguarding letter',
  section7_report: 'Section 7 report',
  section37_report: 'Section 37 report',
  risk_assessment_16a: '16a risk assessment',
  important_address_and_contact_details: 'Important information about your address and contact details',
  dna_reports: 'DNA reports',
  privacy_notice: 'Privacy notice',
  special_measures: 'Special measures',
  notice_of_hearing: 'Notice of hearing',
  support_you_need_during_your_case: 'Support you need during your case',
};
