export const en = {
  caseNumber: 'Case number',
  uploadDocuments: {
    title: 'Select the type of document',
    pageCaption: 'Upload documents',
    content: 'The court will tell you in a letter or email which documents or material you need to submit.',
    documentSectionTitles: {
      witnessStatementsAndEvidence: 'Witness statements and evidence',
      applications: 'Applications',
      expertReports: 'Expert reports',
      otherDocuments: 'Other documents',
    },
    documentCategoryLabels: {
      positionStatements: 'Your position statement',
      witnessStatements: 'Your witness statements',
      otherPeopleWitnessStatements: "Other people's witness statements",
      emailImagesMedia: 'Emails, screenshots, images and other media files',
      medicalRecords: 'Medical records',
      lettersFromSchool: 'Letters from school',
      tenancyMortgageAgreements: 'Tenancy and mortgage agreements',
      previousOrdersSubmitted: 'Previous orders submitted with application',
      medicalReports: 'Medical reports',
      paternityTestReports: 'Paternity test reports',
      drugAndAlcoholTests: 'Drug and alcohol tests (toxicology)',
      policeReports: 'Police reports',
      otherDocuments: 'Other documents',
    },
  },
  viewDocuments: {
    title: 'All documents',
    documentSectionTitles: {
      applicationPacks: 'Application packs',
      ordersFromTheCourt: 'Orders from the court',
      applicantsDocuments: "Applicant's documents",
      respondentsDocuments: "Respondent's documents",
      attendingTheHearing: 'Attending the hearing',
    },
    documentCategoryLabels: {
      packServed: 'Your served application pack',
      packToBeServed: 'Application pack to be served on the respondent',
      positionStatements: "{partyName}'s position statements",
      witnessStatements: "{partyName}'s witness statements",
      otherPeopleWitnessStatements: "Other people's witness statements",
      medicalRecords: 'Medical records',
      medicalReports: 'Medical reports',
      DNAReports: 'DNA reports',
      drugAndAlcoholTests: 'Drug and alcohol tests (toxicology)',
      policeReports: 'Police reports',
    },
  },
};

export const cy: typeof en = {
  caseNumber: 'Rhif yr achos',
  uploadDocuments: {
    title: 'Dewiswch y math o ddogfen',
    pageCaption: 'Upload documents - welsh',
    content: 'The court will tell you in a letter or email which documents or material you need to submit. - welsh',
    documentSectionTitles: {
      witnessStatementsAndEvidence: 'Datganiadau tyst a thystiolaeth',
      applications: 'Ceisiadau',
      expertReports: 'Adroddiadau arbenigwyr',
      otherDocuments: 'Dogfennau eraill',
    },
    documentCategoryLabels: {
      positionStatements: 'Eich datganiadau safbwynt',
      witnessStatements: 'Eich datganiadau tyst',
      otherPeopleWitnessStatements: 'Datganiadau tyst pobl eraill',
      emailImagesMedia: 'Negeseuon e-bost, cipluniau, delweddau a ffeiliau cyfryngau eraill',
      medicalRecords: 'Cofnodion meddygol',
      lettersFromSchool: 'Llythyrau gan yr ysgol',
      tenancyMortgageAgreements: 'Tenantiaeth a morgais',
      previousOrdersSubmitted: "Gorchmynion blaenorol wedi'u cyflwyno gyda'r cais",
      medicalReports: 'Adroddiadau meddygol',
      paternityTestReports: 'Adroddiadau profion tadolaeth',
      drugAndAlcoholTests: 'Profion cyffuriau ac alcohol (tocsicoleg)',
      policeReports: "Adroddiadau'r heddlu",
      otherDocuments: 'Dogfennau eraill',
    },
  },
  viewDocuments: {
    title: 'Pob dogfen',
    documentSectionTitles: {
      applicationPacks: 'Application packs - welsh',
      ordersFromTheCourt: 'Gorchmynion gan y llys',
      applicantsDocuments: 'Dogfennau’r Ceisydd',
      respondentsDocuments: "Dogfennau'r Atebydd",
      attendingTheHearing: 'Mynychu’r gwrandawiad',
    },
    documentCategoryLabels: {
      packServed: 'Your served application pack - welsh',
      packToBeServed: 'Application pack to be served on the respondent - welsh',
      positionStatements: 'Datganiadau safbwynt {partyName}',
      witnessStatements: 'Datganiadau tyst {partyName}',
      otherPeopleWitnessStatements: 'Datganiadau tyst pobl eraill',
      medicalRecords: 'Cofnodion meddygol',
      medicalReports: 'Adroddiadau meddygol',
      DNAReports: 'Adroddiadau DNA',
      drugAndAlcoholTests: 'Profion cyffuriau ag alcohol (tocsicoleg)',
      policeReports: 'Adroddiadau gan yr heddlu',
    },
  },
};
