export const documents_list_items_en = {
  your_position_statements: 'Your position statements',
  your_witness_statements: 'Your witness statements',
  other_witness_statements: "Other people's witness statements",
  mail_screenshots_media_files: 'Emails, screenshots, images and other media files',
  medical_records: 'Medical records',
  letters_from_school: 'Letters from school',
  tenancy_mortgage_agreements: 'Tenancy and mortgage agreements',
  previous_orders_submitted: 'Previous orders submitted with application',
  medical_reports: 'Medical reports',
  paternity_test_reports: 'Paternity test reports',
  drug_and_alcohol_tests: 'Drug and alcohol tests (toxicology)',
  police_reports: 'Police reports',
  other_documents: 'Other documents',
};

export const documents_list_items_cy = {
  your_position_statements: 'Eich datganiadau sefyllfa',
  your_witness_statements: 'Eich datganiadau tyst',
  other_witness_statements: 'Datganiadau tystion pobl eraill',
  mail_screenshots_media_files: 'E-byst, sgrinluniau, delweddau a ffeiliau cyfryngau eraill',
  medical_records: 'Cofnodion meddygol',
  letters_from_school: "Llythyrau o'r ysgol",
  tenancy_mortgage_agreements: 'Cytundebau tenantiaeth a morgais',
  previous_orders_submitted: "Gorchmynion blaenorol wedi'u cyflwyno gyda'r cais",
  medical_reports: 'Medical reports',
  paternity_test_reports: 'Adroddiadau profion tadolaeth',
  drug_and_alcohol_tests: 'Profion cyffuriau ac alcohol (tocsicoleg)',
  police_reports: "Adroddiadau'r heddlu",
  other_documents: 'Dogfennau eraill',
};
