export enum HTML {
  LIST_ITEM = '<li>',
  LIST_ITEM_END = '</li>',
  UNORDER_LIST = '<ul>',
  UNORDER_LIST_END = '</ul>',
  NESTED_LIST_ITEM = '<li class="govuk-!-padding-top-1 govuk-!-padding-bottom-1">',
  NESTED_LIST_ITEM_END = '</li>',
  H4 = '<h4>',
  H3 = '<h3>',
  P = '<p>',
  H4_CLOSE = '</h4>',
  H3_CLOSE = '</h3>',
  P_CLOSE = '</p>',
  RULER = '<hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">',
  BOTTOM_PADDING_3 = '<div class="govuk-!-padding-bottom-3">',
  BOTTOM_TOP_3 = '<div class="govuk-!-padding-top-3">',
  BOTTOM_PADDING_CLOSE = '</div>',
  TOP_PADDING_CLOSE = '</div>',
}
