export enum HTML {
  LIST_ITEM = '<li>',
  LIST_ITEM_END = '</li>',
  UNORDER_LIST = '<ul class="govuk-list govuk-list--bullet">',
  UNORDER_LIST_END = '</ul>',
  NESTED_LIST_ITEM = '<li>',
  NESTED_LIST_ITEM_END = '</li>',
  H1 = '<h1>',
  H1_CLOSE = '</h1>',
  H2 = '<h2>',
  H2_CLOSE = '</h2>',
  H4 = '<h4>',
  H3 = '<h3>',
  P = '<p>',
  H4_CLOSE = '</h4>',
  H3_CLOSE = '</h3>',
  P_CLOSE = '</p>',
  RULER = '<hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">',
  BOTTOM_PADDING_3 = '<div class="govuk-!-padding-bottom-3">',
  BOTTOM_TOP_3 = '<div class="govuk-!-padding-top-3">',
  BOTTOM_PADDING_CLOSE = '</div>',
  TOP_PADDING_CLOSE = '</div>',
  BREAK = '<br>',
  H4_SECTION_TITLE = '<h4 class="app-task-list__section">',
  STATEMENT_OF_TRUTH_HEADING_H2 = "<h2 class='govuk-heading-l govuk-!-padding-bottom-3 govuk-!-padding-top-2'>",
  STATEMENT_OF_TRUTH_H3 = "<h3 class='govuk-heading-m govuk-!-padding-bottom-4'>",
  STATEMENT_OF_TRUTH_H3_CLOSE = '</h3>',
  BOLD = '<b>',
  BOLD_CLOSE = '</b>',
  DESCRIPTION_LIST = '<dl class="govuk-summary-list">',
  DESCRIPTION_LIST_END = '</dl>',
  DESCRIPTION_TERM_ELEMENT = '<dt class="govuk-summary-list__key">',
  DESCRIPTION_TERM_ELEMENT_END = '</dt>',
  NEW_ROW_START = '<div class="govuk-summary-list__row">',
  NEW_ROW_START_NO_BORDER = '<div class="govuk-summary-list__row border-bottom--none">',
  ROW_END = '</div>',
  DESCRIPTION_TERM_DETAIL = '<dd class="govuk-summary-list__value">',
  DESCRIPTION_TERM_DETAIL_LIST = '<dd class="govuk-summary-list__key">',
  DESCRIPTION_TERM_DETAIL_END = '</dd>',
}
